# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import myitems_pb2 as myitems__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in myitems_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ItemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItemById = channel.unary_unary(
                '/myitems.ItemService/GetItemById',
                request_serializer=myitems__pb2.ItemRequest.SerializeToString,
                response_deserializer=myitems__pb2.ItemResponse.FromString,
                _registered_method=True)
        self.ListAllItems = channel.unary_stream(
                '/myitems.ItemService/ListAllItems',
                request_serializer=myitems__pb2.Empty.SerializeToString,
                response_deserializer=myitems__pb2.ItemResponse.FromString,
                _registered_method=True)
        self.AddItems = channel.stream_unary(
                '/myitems.ItemService/AddItems',
                request_serializer=myitems__pb2.ItemName.SerializeToString,
                response_deserializer=myitems__pb2.ItemsCount.FromString,
                _registered_method=True)
        self.EditItemById = channel.unary_unary(
                '/myitems.ItemService/EditItemById',
                request_serializer=myitems__pb2.ItemRequest.SerializeToString,
                response_deserializer=myitems__pb2.ItemResponse.FromString,
                _registered_method=True)
        self.DeleteItemById = channel.unary_unary(
                '/myitems.ItemService/DeleteItemById',
                request_serializer=myitems__pb2.ItemRequest.SerializeToString,
                response_deserializer=myitems__pb2.ItemsCount.FromString,
                _registered_method=True)
        self.ChatAboutItems = channel.stream_stream(
                '/myitems.ItemService/ChatAboutItems',
                request_serializer=myitems__pb2.ChatMessage.SerializeToString,
                response_deserializer=myitems__pb2.ChatMessage.FromString,
                _registered_method=True)


class ItemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetItemById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItems(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditItemById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItemById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatAboutItems(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItemById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemById,
                    request_deserializer=myitems__pb2.ItemRequest.FromString,
                    response_serializer=myitems__pb2.ItemResponse.SerializeToString,
            ),
            'ListAllItems': grpc.unary_stream_rpc_method_handler(
                    servicer.ListAllItems,
                    request_deserializer=myitems__pb2.Empty.FromString,
                    response_serializer=myitems__pb2.ItemResponse.SerializeToString,
            ),
            'AddItems': grpc.stream_unary_rpc_method_handler(
                    servicer.AddItems,
                    request_deserializer=myitems__pb2.ItemName.FromString,
                    response_serializer=myitems__pb2.ItemsCount.SerializeToString,
            ),
            'EditItemById': grpc.unary_unary_rpc_method_handler(
                    servicer.EditItemById,
                    request_deserializer=myitems__pb2.ItemRequest.FromString,
                    response_serializer=myitems__pb2.ItemResponse.SerializeToString,
            ),
            'DeleteItemById': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItemById,
                    request_deserializer=myitems__pb2.ItemRequest.FromString,
                    response_serializer=myitems__pb2.ItemsCount.SerializeToString,
            ),
            'ChatAboutItems': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatAboutItems,
                    request_deserializer=myitems__pb2.ChatMessage.FromString,
                    response_serializer=myitems__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myitems.ItemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myitems.ItemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ItemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItemById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myitems.ItemService/GetItemById',
            myitems__pb2.ItemRequest.SerializeToString,
            myitems__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/myitems.ItemService/ListAllItems',
            myitems__pb2.Empty.SerializeToString,
            myitems__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItems(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/myitems.ItemService/AddItems',
            myitems__pb2.ItemName.SerializeToString,
            myitems__pb2.ItemsCount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditItemById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myitems.ItemService/EditItemById',
            myitems__pb2.ItemRequest.SerializeToString,
            myitems__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteItemById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myitems.ItemService/DeleteItemById',
            myitems__pb2.ItemRequest.SerializeToString,
            myitems__pb2.ItemsCount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatAboutItems(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/myitems.ItemService/ChatAboutItems',
            myitems__pb2.ChatMessage.SerializeToString,
            myitems__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
